import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import NavBarMain from "@/components/Navbar/NavbarMain";
import Footer from "@/components/Footer/Footer";
import PremiumNavbar from "@/components/ExtraDesigns/PremiumNavbar";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
        suppressHydrationWarning={true}
      >
        <NavBarMain/>
        {/* <PremiumNavbar/> */}
        {children}
        <Footer/>
      </body>
    </html>
  );
}
