# Generated by Django 5.2.7 on 2025-10-30 07:23

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TM_photography', '0002_eventbooking_delete_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventbooking',
            name='phone',
            field=models.CharField(max_length=15, validators=[django.core.validators.RegexValidator(message='Phone number must contain only digits (10–15 digits).', regex='^\\d{10,15}$')]),
        ),
    ]
